version: '2.2'
volumes:
    resin-data:
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    build: ./data
    volumes:
      - 'resin-data:/data'
    expose:
      - "8080"
  picamera:
    restart: always
    build: ./picamera
    volumes:
      - 'resin-data:/data'
    expose:
      - "3000"
    privileged: true
  gpio:
    build: ./gpio
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
