version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "80"
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    build: ./data
    volumes:
      - 'resin-data:/data'
    expose:
      - "8080"
  picamera:
    restart: always
    build: ./picamera
    volumes:
      - 'resin-data:/data'
    expose:
      - "3000"
    privileged: true
