version: '2'
volumes:
    resin-data:
    picam_config:
services:
  frontend:
    build: ./frontend
    volumes:
      - 'resin-data:/data'
    ports:
      - "80:80"
  data:
    build: ./data
    expose:
      - "8080"
  nodejs-picam:
    restart: always
    build: ./nodejs-picam
    ports:
      - "3333:3333"
    volumes:
      - 'resin-data:/data'
      - 'picam_config:photo.js'
    privileged: true

#  picamera:
#    restart: always
#    build: ./picamera
#    volumes:
#      - 'resin-data:/data'
#    privileged: true
#  video-stream:
#    build: ./video-stream
#    expose:
#      - "3000"

#  gpio:
#    build: ./gpio
#    devices:
#      - "/dev/i2c-1:/dev/i2c-1"
#      - "/dev/mem:/dev/mem"
#    cap_add:
#      - SYS_RAWIO

#   proxy:
#    build: ./haproxy
#    depends_on:
#      - frontend
#      - data
#    ports:
#      - "80:80"
