version: '2'
services:
  frontend:
    build: ./frontend
    expose:
      - "81"
  proxy:
    build: ./haproxy
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    build: ./data
    expose:
      - "8080"
  picamera:
    restart: always
    build: ./picamera
    expose:
      - "80"
    depends_on:
      - data
    privileged: true
